### ISSUE TITLE
Non -Sequitur comic is not updating

### ISSUE THREAD

**Issue by othalan** [ArtskydJ/comicsrss.com#133]
The comic Non -Sequitur is not updating the past few days...

**Comment by ArtskydJ** [comment]
It looks like the [RSS feed](https://www.comicsrss.com/rss/nonsequitur.rss) is currently up-to-date.  Is this still a problem for you?

**Comment by othalan** [comment]
It started updating again on 2 August after a week of no updates

**Comment by ArtskydJ** [comment]
I don't know what went wrong.  I wondered if this was an instance of #128.  However, it appears to be a different issue, because the RSS file was updated every day: https://github.com/ArtskydJ/comicsrss.com/commits/gh-pages/rss/nonsequitur.rss

It seems that somewhere between the source code on GitHub and your feed reader, something didn't update.  Maybe the gh-pages deploy failed?  Maybe some caching issue with your feed reader?  Could be that something went wrong on my end that I don't understand?

What feed reader do you use?

**Comment by othalan** [comment]
I use [Feedly](https://feedly.com). It will sometimes delay updates by several hours but I have never seen it fail to update a feed for several days (several years of use).

I _think_ I remember checking the feed directly on comicsrss.com and seeing that it too was behind. That would be normal for me before I submit an issue like this. But to be honest I am not certain. I cannot rule out feedly being the problem. Though ordinarily all comics I follow from comicsrss.com either work or fail the exact same within feedly (except Dilbert), which is why I thought there might be a problem and submitted this issue.

If this happens again, I can look more carefully at feedly vs comicsrss.com vs the github commit history.

Thank you for providing a wonderful service to all of us who prefer an rss reader for our comics!

**Comment by ArtskydJ** [comment]
Feel free to re-open if it happens again.
