### ISSUE TITLE
improve frontend

### ISSUE THREAD

**Issue by Bhanu-code** [ArtskydJ/comicsrss.com#138]
frontend appearence of the project can be improved. Please assign me under hactoberfest if you want.

**Comment by itsjustneo-xo** [comment]
I'd like to work on this

**Comment by ArtskydJ** [comment]
The frontend appearance can definitely be improved.  I'm hesitant to give blanket approval since I'll feel bad if I don't end up merging.  If asked about specific improvements, I'm happy to give a :+1: or :-1:.

There are things that make frontends look better, but also makes them harder to use.  I'm not interested in stuff that makes it harder to use. Examples of things I don't want:
- Hide things behind a click
- Bad contrast between text and background.  (I want AAA contrast. https://accessibleweb.com/color-contrast-checker/)
- Unclear buttons (No labels, or non-descriptive labels)

I'd prefer that there isn't a big revamp of how the site is generated, or 3rd party stuff like bootstrap.

Some issues with the site that I'd happily let others work on:
- Search area
	- The search bar is not obviously an input
	- There should probably be a placeholder instead of the "Search" label
	- There should probably be space between the search input and the list of feeds
	- Maybe "Filter" would be more accurate than "Search"
- List of feeds
	- Some titles are cut off
	- The title and the author are merged into one string.  I wonder about showing the author smaller below the title.  I think it would look bad to make it smaller on the same line.  I still want the filter to work with the author.
	- "Source" and "Preview" use the same icon.  See #136.
	- Half of the list is taken up with the same links again and again.  The easy ways to make this look nicer decreases the usability, IMO, so maybe check with me before spending a bunch of time on this.
	- All the links are a bit too close, but I don't want them using up any more space, so I don't have a clear solution.
- Other
	- The "contact" link in the header is basically useless, and could be deleted
	- The pink background for the "contact" section is ugly
	- "Browse" and "Contact" are different sizes/weights
	- "Browse" looks out of place, but deleting it makes the filter section less obvious
	- The whole site lacks color, which is probably part of why I added the orange RSS icon.

**Comment by ArtskydJ** [comment]
> Please assign me under hactoberfest

Are there specific steps I need to perform other than having a "hacktoberfest" tag on the repo?

**Comment by itsjustneo-xo** [comment]
I'd be happy to work on the changes you mentioned and they should be simple enough to implement.

**Comment by itsjustneo-xo** [comment]
> > Please assign me under hactoberfest
> 
> Are there specific steps I need to perform other than having a "hacktoberfest" tag on the repo?

I don't think so. You're good

**Comment by ArtskydJ** [comment]
I was disappointed to see [no more T-shirts for hacktoberfest anymore](https://hacktoberfest.com/about/#digital-rewards).  Just in case that's your main motivation (as it was for me), I figured I'd save you some time 😛

**Comment by itsjustneo-xo** [comment]
> I was disappointed to see [no more T-shirts for hacktoberfest anymore](https://hacktoberfest.com/about/#digital-rewards). Just in case that's your main motivation (as it was for me), I figured I'd save you some time 😛

It was how I got to know about hacktoberfest but I stayed for open-source. I've created a couple open-source projects of my own, but always wanted to contribute on others' projects so it's a great time :D

**Comment by Bhanu-code** [comment]
soon I will raise a PR

**Comment by Bhanu-code** [comment]
elements in the table are close to each other, a little bit of padding would be better. Other than comics name, preview , copy url and source is repetetive, can be imrpoved with on hover visilibility, and a bit of theming and colors will make the appearence much better.

**Comment by ArtskydJ** [comment]
> elements in the table are close to each other, a little bit of padding would be better.

More padding would look nicer, but would cut off more of the comic name/author.  Or the table needs to be wider.  I'd rather it not be wider because of mobile devices.  It's already pretty rough on small screens.

> Other than comics name, preview , copy url and source is repetitive, can be improved with on hover visibility

I don't want the button labels to only be visible on hover, if that's what you're recommending.

> a bit of theming and colors will make the appearance much better.

If you want to take a stab at it, you sure can 👍  I'd like to avoid large 3rd party libraries on the client.
