### ISSUE TITLE
GoComics not updating tonight

### ISSUE THREAD

**Issue by ghost** [ArtskydJ/comicsrss.com#94]
The comics did update up right after your message yesterday, but they're still not automatically updated so far tonight (over 2 hours after updated on GoComics site).   I did refresh, multiple times.

**Comment by ArtskydJ** [comment]
Thanks for the report. I'd made a typo in a part of the code that rarely runs. This caused the automated build to fail. I got an automated email that it failed, but due to my sleep schedule I don't tend to see the automated emails until many hours later.

Anyway, that issue is fixed, and the updated RSS feeds are live. Hopefully next time I make a change, it doesn't break the build like I did last two days!
